name: Deploy Dildhani website to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build (verify locally)
        run: |
          cd website
          npm ci
          npm run build
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /projects/deg/website
            git pull origin main
            npm ci
            npm run build
            pm2 restart deg-website || pm2 start npm --name "deg-website" -- start
            pm2 save
